routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect('home/landingpage');
});
Route::get("home", function() {return redirect('home/landingpage');});
Route::get("home/landingpage", function() {return view("landingpage");});
Route::get("home/location", function() {return view("location");});

Route::get("home/towns", function() {return view("towns");});
Route::post('home/towns', 'App\Http\Controllers\GetTownsController@read');

Route::get("home/newtown", function() {return view("newtown");});
Route::post('home/newtown', 'App\Http\Controllers\NewTown@create');

Route::get("home/contact", function() {return view("contact");});
Route::post('home/contact', 'App\Http\Controllers\ContactFormController@create');
Route::get("home/messages", 'App\Http\Controllers\MessagesController@read');

use App\Http\Controllers\GalleryController;
Route::resource('gallery',GalleryController::class);

use App\Http\Controllers\PostController;
Route::resource('posts', PostController::class);

resources/views/contact.blade.php
@extends("mainpage")
@section("content")
<div class="hero d-flex justify-content-center align-items-center">
  <div class="container text d-flex flex-column my-5">

    <form method="post" action="contact">
      @csrf 
      @if (count($errors) > 0)
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
        @endif  
      <div class="mb-3">
        <label for="exampleInput" class="form-label">Your name </label>
        <input type="text" class="form-control" id="exampleInput" name="from" minlength=0 maxlength=20  required>
        <label for="exampleInput2" class="form-label">Message</label>
        <input type="text" class="form-control" id="exampleInput2" name="message" minlength=10 maxlength=255 required>
      </div>

      <button type="submit" class="btn btn-primary">Submit</button>
    </form> 

    @if (isset($mes))
    <h1 class="my-5">Successful addition</h1>
    @endif 
  </div>
</div>
@stop

resources/views/create.blade.php
@extends('parent')
@section('main')
    @if($errors->any())
    <div class="alert alert-danger">
        <ul>
        @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
        </ul>
    </div>
    @endif
    <h4 align="center">Upload Image</h4>
    <div align="right">
        <a href="{{ route('gallery.index') }}" class="btn btn-dark">Back</a>
    </div>
    <form method="post" action="{{ route('gallery.store') }}" enctype="multipart/form-data">
        <div class="form-group">
            <label class="col-md-4 text-right">Title</label>
            <div>
                <input type="text" name="title" class="form-control input-lg" />
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-8">
                <input type="file" name="image" />
            </div>
        </div>
        <div class="form-group text-center">
            <input type="submit" name="add" class="btn btn-secondary input-lg" value="Add" />
        </div>
    </form>
@endsection

resources/views/edit.blade.php
@extends('parent')
@section('main')
    <h4 align="center">Edit Record</h4>
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
        </ul>
    </div>
    @endif
    <div align="right">
        <a href="{{ route('gallery.index') }}" class="btn btn-dark">Back</a>
    </div>
    <br />
    <form method="post" action="{{ route('gallery.update', $data->id) }}" enctype="multipart/form-data">
        <div class="form-group">
            <label class="col-md-4 text-right">Title</label>
            <div>
                <input type="text" name="title" value="{{ $data->title }}" class="form-control input-lg" />
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <input type="hidden" name="_method" value="PUT">
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-8">
                <input type="file" name="image" />
                <img src="{{ URL::to('/') }}/images/{{ $data->image }}" class="img-thumbnail" width="100" />
                <input type="hidden" name="hidden_image" value="{{ $data->image }}" />
            </div>
        </div>
        <div class="form-group text-center">
            <input type="submit" name="edit" class="btn btn-secondary input-lg" value="Edit" />
        </div>
    </form>
@endsection

resources/views/header.blade.php
@section("header")
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">TownsFinder</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="./location">Location</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="./towns">Towns</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="./newtown">New Town</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="./contact">Contact</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="./messages">Messages</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/gallery">Gallery</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/posts">Blog</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
@show

resources/views/index2.blade.php
@extends("master")
@section("title") Posts @endsection
@section("content")
<div class="row mb-4">
<a href="/home" class="btn btn-dark">Back to home</a>
    <div class="col-xl-6">
        @if(Session::has('success'))
            <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">× </button>
                {{Session::get('success')}}
            </div>
        @endif
        @if(Session::has('failed'))
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">× </button>
                {{Session::get('failed')}}
            </div>
        @endif 
    </div>
    <div class="col-xl-6 text-right">
        <a href="{{route('posts.create')}}" class="btn btn-dark "> Add New </a>
    </div>
</div>
<table class="table table-striped">
    <thead>
        <th> Id </th>
        <th> Title </th>
        <th> Description </th>
        <th> Action </th>
    </thead>
    <tbody>
        @if(count($posts) > 0)
            @foreach($posts as $post)
                <tr>
                    <td> {{$post->id}} </td>
                    <td> {{$post->title}} </td>
                    <td> {{$post->description}} </td>
                    <td>
                        <form action="{{route('posts.destroy', $post->id)}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <a href="{{route('posts.show', $post->id)}}" class="btn btn-sm btn-secondary"> Show </a>
                            <a href="{{route('posts.edit', $post->id)}}" class="btn btn-sm btn-secondary"> Edit </a>
                            <button type="submit" class="btn btn-sm btn-secondary"> Delete </button>
                        </form>
                    </td>
                </tr>
            @endforeach
        @endif
    </tbody>
</table>
{!! $posts->links() !!}
@endsection

resources/views/landingpage.blade.php
@extends("mainpage")
@section("content")
<div class="hero d-flex justify-content-center align-items-center">
  <div class="container text d-flex flex-column my-5">
    <h1 class="text-center mb-3">Welcom to our website!</h1>

    <iframe id="video" src="https://www.youtube.com/embed/5ftGaUWPE1c" title="YouTube video player"
      frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
      allowfullscreen></iframe>
      <br>
    <video controls>
      <source src="/video.mp4" type="video/mp4">
      Your browser does not support the video tag.
    </video>
  </div>
</div>
@stop

resources/views/location.blade.php
@extends("mainpage")
@section("content")
<div class="hero d-flex justify-content-center align-items-center">
  <div class="container text d-flex flex-column my-5">
  <iframe id="map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d172572.09758799357!2d18.990220687032146!3d47.481360188070994!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4741c334d1d4cfc9%3A0x400c4290c1e1160!2sBudapest!5e0!3m2!1shu!2shu!4v1650812899491!5m2!1shu!2shu"  style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
  </div>
</div>
@stop

resources/views/mainpage.blade.php
<!doctype html>
<html lang="en">
  <head>
    <title>My Website</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/style.css" />
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
  <body>
    <div class="header">
      @include("header")
    </div>
    <div class="content">
      @yield("content")
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/master.blade.php
<!doctype html>
<html lang="en">
  <head>
    <title> Laravel 8 CRUD - @yield('title') - Programming Fields</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>
  <body>
      <div class="container mt-5">
          @yield('content')
      </div>
  </body>
</html>

resources/views/messages.blade.php
@extends("mainpage")
@section("content")
<div class="hero d-flex justify-content-center align-items-center">
  <div class="container text d-flex flex-column my-5">

      @foreach ($msg as $m)
      <ul class="list-group my-5">
        <li class="list-group-item">From: {{$m->from}}</li>
        <li class="list-group-item">Message: {{$m->message}}</li>
     </ul>
      @endforeach
    
  </div>
</div>
@stop

resources/views/parent.blade.php
<html>
    <head>
        <title>Laravel Crud Application</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="container">
            <br />
            <a href="/home" class="btn btn-dark">Back to home</a>
            <h1 align="center">Image Gallery</h1>
            <br />
            @yield('main')
        </div>
    </body>
</html>

resources/views/show-post.blade.php
@extends("master")
@section("title") Show Post @endsection
@section("content")
<div class="container">
    <div class="row">
        <div class="col-xl-12 col-lg-12 text-right">
            <a href="{{route('posts.index')}}" class="btn btn-dark"> Back to Posts </a>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 m-auto">
            <div class="card shadow">
                <div class="card-header">
                    <h4 class="card-title"> Show Post </h4>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="title"> Title </label>
                        <input type="text" readonly name="title" class="form-control" id="title" value="@if(!empty($post)) {{$post->title}} @endif">
                    </div>
                    <div class="form-group">
                        <label for="description"> Description </label>
                        <textarea class="form-control" readonly name="description" id="description">@if(!empty($post)) {{$post->description}} @endif</textarea>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/towns.blade.php
@extends("mainpage")
@section("content")
<div class="hero d-flex justify-content-center align-items-center">
  <div class="container text d-flex flex-column my-5">

    <form method="post" action="towns">
      @csrf 
      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Enter a County ID (1-20)</label>
        <input type="number" class="form-control" id="exampleInputEmail1" name="countyid_form" min=1 max=20>
      </div>

      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    @if (isset($towns) > 0)
    <ul class="list-group my-5">
      @foreach ($towns as $town)
        <li class="list-group-item">{{$town->tname}}</li>
      @endforeach
    </ul>
    @endif  
  </div>
</div>
@stop

resources/views/view.blade.php
@extends('parent')
@section('main')
    <h4 align="center">View Image</h4>
    <div class="jumbotron text-center">
        <div align="right">
            <a href="{{ route('gallery.index') }}" class="btn btn-dark">Back</a>
        </div>
        <br />
        <img src="{{ URL::to('/') }}/images/{{ $data->image }}" class="img-thumbnail" />
        <h3> {{ $data->title }} </h3>
    </div>
@endsection